### ISSUE TITLE
关于KD-TREE

### ISSUE THREAD

**Issue by EillotY** [CommissarMa/Crowd_counting_from_scratch#2]
首先我想询问您的是为何采用KD - TREE 对于密度图的作用是什么（就是为何您采用这种方式就会对生成得密度图有更高得准确度嘛【这点很重要】），这个是我最近没有搞懂的一个最主要的一件事；还有一件事是为何选取得叶子节点是2048以及K为4；还有最后一个问题，我并没有查到scipy.spatial.KDTree的一个具体介绍（只找到了参数的介绍，没有查到它的源代码），就是想问它的是按照维度最大方差进行建树的嘛。希望您能回复，感谢。

**Comment by CommissarMa** [comment]
@EillotY MCNN的文章里用了K近邻来生成密度图，你可以看下文章。然后K近邻最快的计算方法是KD-TREE，因此CSRNet的作者使用了这个方法[link](https://github.com/leeyeehoo/CSRNet-pytorch/blob/master/make_dataset.ipynb)

**Comment by EillotY** [comment]
好的 感谢回复
