### ISSUE TITLE
Some problem of k_nearest_gaussian_kernel.py

### ISSUE THREAD

**Issue by ExpectoPatronumCG** [CommissarMa/Crowd_counting_from_scratch#4]
I found that if I use this method to generate the density maps, the count of the density map is different from the original .mat file. Is there something wrong? For example, the IMG_2 in ShanghaiTechA train data,  the count of GT_IMG_2.mat  is 707. But the count of the density map generated by your code is 698.
Thanks!

你好，我发现用你的代码生成的密度图和原始的.mat文件里的数目有些偏差，比如ShanghaiTech A里第二张图，原始的.mat文件中的label数是707，但用你的code生成的密度图sum之后是698。不知道是否有什么问题呢？还有你尝试过别的sigma和k取值的影响吗。
感谢!

**Comment by CommissarMa** [comment]
问题不大的。实在担心的话，你把该密度图先除以698再乘707就可以保证人数一致了。
